FROM ubuntu:16.04
RUN apt-get update && \
	apt-get install -y \
			gcc \
			g++ \
			make \
			libc6-dev-i386 \
			vim \
			nasm \
			libx11-dev \
			libxrandr-dev

RUN apt-get install -y \
			ctags \
			cscope 

