#!/bin/bash

xhost +local:docker

source ./_env
BOCHS_HOME=$CWD/bochs

sudo docker run  -it  --rm  \
				--name minixDebug \
				-e DISPLAY  \
				-v /tmp/.X11-unix:/tmp/.X11-unix  \
				-v "$(pwd)/src":$MYOS_HOME  \
				-v "$(pwd)/bochs":$BOCHS_HOME  \
				-v "$(pwd)/tmp":$TMP_DIR  \
				-w $MYOS_HOME \
				-p 1234:1234  \
				$IMAGE

# --net=host  --ipc=host  --privileged  \
# Other might face issue regarding the image not getting rendered on screen or getting a blank screen with no image, 
# for them add --env="_X11_NO_MITSHM=1" to the above script while running the docker image. It will solve the problem.
