MY_HOME = ../..
LIB_NAME = myc

OBJS_M32 = \
		data.o \
		fillbuf.o \
		fflush.o \
		flushbuf.o \
		fopen.o \
		freopen.o \
		fclose.o \
		tmpfile.o \
		tmpnam.o \
		icompute.o \
		setbuf.o \
		setvbuf.o \
		fprintf.o \
		printf.o \
		sprintf.o \
		vfprintf.o \
		vprintf.o \
		vsprintf.o \
		fscanf.o \
		scanf.o \
		sscanf.o \
		vscanf.o \
		vsscanf.o \
		fgetc.o \
		fgets.o \
		fputc.o \
		fputs.o \
		gets.o \
		puts.o \
		ungetc.o \
		fread.o \
		fwrite.o \
		fgetpos.o \
		fseek.o \
		fsetpos.o \
		ftell.o \
		rewind.o \
		perror.o 


all: build

include ../commonlib.mk

build: $(LIB_M32)

clean: clean32
