MY_HOME = ../..
LIB_NAME = myc

OBJS_M32 = \
		data.o \
		fillbuf.o \
		fflush.o \
		flushbuf.o \
		fopen.o \
		freopen.o \
		fclose.o \
		tmpfile.o \
		tmpnam.o \
		icompute.o


all: build

include ../commonlib.mk

build: $(LIB_M32)

clean: clean32
