all:
	cd libpci && $(MAKE)
	cd libdriver && $(MAKE)
	cd at_wini && $(MAKE)
	cd memory && $(MAKE)
	cd tty && $(MAKE)

clean:
	cd libpci && $(MAKE) clean
	cd libdriver && $(MAKE) clean
	cd at_wini && $(MAKE) clean
	cd memory && $(MAKE) clean
	cd tty && $(MAKE) clean
