LIB_NAME = myc

OBJS_M32 = memcpy.o \
		   strcat.o \
		   strcpy.o \
		   strlen.o \
		   strcmp.o

OBJS_M16 = memcpy.o \
		   strcat.o \
		   strcpy.o \
		   strlen.o \
		   strcmp.o
	

include ../commonlib.mk
