MY_HOME = ../../..
LIB_NAME = myc

OBJS_M32 = \
		io_inb.o \
		io_inw.o \
		io_inl.o \
		io_outb.o \
		io_outw.o \
		io_outl.o \
		io_intr.o \
		getprocessor.o


all: build

include ../../commonlib.mk

build: $(LIB_M32)

clean: clean32
