#!/bin/sh -


if [ $# != 1 ]
then
	echo "USAGE: $0 builtins.table"
	exit 1
fi
BLTINS=$1
DIR=..

temp=/tmp/ka$$
exec > $DIR//builtins.c
cat <<\!
/*
 * This file was generated by the mkbuiltins.sh program.
 */

#include "shell.h"
#include "builtins.h"

!
sed -e '/^#/d
	s/	/ /g
	s/ #.*//
	/^ *$/d
	/-j/d'	$BLTINS > $temp

sed -e 's/ .*//
	s/\(.*\)/int \1();/' $temp

echo '
int (*const builtinFunc[])() = {'

sed -e 's/ .*//
	s/\(.*\)/	\1,/' $temp

echo '};

const BuiltinCmd builtinCmd[] = {'
i=0
while read line
do
	set -$- $line
	shift
	for fun
	do
		echo "	{\"$fun\", $i},"
	done
	i=`expr $i + 1`
done < $temp
echo '	{NULL, 0}
};'

exec > $DIR/builtins.h
cat <<\!
/*
 * This file was generated by the mkbuiltins.sh program.
 */
!
i=0
tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ < $temp |
	while read line
	do
		set -$- $line
		echo "#define $1 $i"
		i=`expr $i + 1`
	done
echo '
typedef struct {
	char *name;
	int code;
} BuiltinCmd;

extern int (*const builtinFunc[])();
extern const BuiltinCmd builtinCmd[];'
rm -f $temp



