#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>


typedef struct {
	int sigNum;		/* Signal number */
	char *name;		/* Signal name (without leading "SIG") */
	char *msg;		/* Description */
} Sig;

static Sig sigTable[] = {
	{SIGHUP, "HUP", "Hangup"},
	{SIGINT, "INT", "Interrupt"},	/* Normally don't print message */
	{SIGQUIT, "QUIT", "Quit"},
	{SIGILL, "ILL", "Illegal instruction"},
	{SIGTRAP, "TRAP", "Trace/BPT trap"},
	{SIGABRT, "ABRT", "abort"},
	{SIGFPE, "FPE", "Floating exception"},
	{SIGKILL, "KILL", "Killed"},
	{SIGBUS, "BUS", "Bus error"},
	{SIGSEGV, "SEGV", "Memory fault"},
	{SIGPIPE, "PIPE", "Broken pipe"},	/* Normall don' print message */
	{SIGALRM, "ALRM", "Alarm call"},
	{SIGTERM, "TERM", "Terminated"},
	{SIGUSR1, "USR1", "User signal 1"},
	{SIGUSR2, "USR2", "User signal 2"},
	{SIGCHLD, "CLD", NULL},
	{SIGSTOP, "STOP", "Stopped"},
	{SIGTSTP, "TSTP", "Stopped"},
	{SIGCONT, "CONT", NULL},
	{SIGTTIN, "TTIN", "Stopped (input)"},
	{SIGTTOU, "TTOU", "Stopped (output)"},
	{0, NULL, NULL}
};

#define MAX_SIG	64

char *sigMsg[MAX_SIG + 1];

static char writer[] = "\
/*\n\
 * This file was generated by the mksignames program.\n\
 */\n\
\n";

int main(int argc, char **argv) {
	FILE *cFile, *hFile;
	int maxSig, i;
	Sig *sigp;

	if ((cFile = fopen("../signames.c", "w")) == NULL) {
		fputs("Can't create signames.c\n", stderr);
		exit(2);
	}
	if ((hFile = fopen("../signames.h", "w")) == NULL) {
		fputs("Can't create signames.h\n", stderr);
		exit(2);
	}
	maxSig = 0;
	for (sigp = sigTable; sigp->sigNum != 0; ++sigp) {
		if (sigp->sigNum < 0 || sigp->sigNum > MAX_SIG)
		  continue;
		sigMsg[sigp->sigNum] = sigp->msg;
		if (maxSig < sigp->sigNum)
		  maxSig = sigp->sigNum;
	}

	fputs(writer, hFile);
	fprintf(hFile, "#define MAX_SIG %d\n\n", maxSig);
	fprintf(hFile, "extern char *const sigMsg[MAX_SIG + 1];\n");

	fputs(writer, cFile);
	fprintf(cFile, "#include \"shell.h\"\n\n");
	fprintf(cFile, "char *const sigMsg[%d] = {\n", maxSig + 1);
	for (i = 0; i <= maxSig; ++i) {
		if (sigMsg[i] == NULL) 
		  fprintf(cFile, "    0,\n");
		else
		  fprintf(cFile, "    \"%s\", \n", sigMsg[i]);
	}
	fprintf(cFile, "};\n");
	return 0;
}






