#!/bin/sh -


# This file describes the nodes used in parse trees. Unindented lines
# contain a node type followed by a structure tag. Subsequent indented
# lines specify the fields of the structure. Several node types can share
# the same structure, in which case the fields of the structure should be
# specified only once.
#
# A field of structure is described by the name of the field followed
# by a type. The currently implemented types are:
#	NodePtr - a pointer to a node
#	NodeList - a pointer to a list of nodes
#	string - a pointer to a nul terminated string
#	int - an integer
#	other - any type that can be copied by assignment
#	temp - a field that doesn't have to be copied when the node is copied
# The last two types should be followed by the text of a C declaration for
# the field.

NSEMI NBinary				# Two commands separated by a semicolon
	type		int
	ch1			NodePtr		# The first child
	ch2			NodePtr		# The second child

NCMD NCmd					# A simple command
	type		int
	backgnd		int			# Set to run command in background
	args		NodePtr		# The arguments
	redirect	NodePtr		# List of file redirections

NPIPE NPipe					# A pipeline
	type		int
	backgnd		int			# Set to run pipeline to background
	cmdList		NodeList	# The commands in the pipeline

NREDIR NRedir				# Redirection (of a complex command)
	type		int
	n			NodePtr		# The command
	redirect	NodePtr		# List of file redirections

NBACKGND NRedir				# Run command in background
NSUBSHELL NRedir			# Run command in a subshell

NAND NBinary				# The && operator
NOR NBinary					# The || operator

NIF NIf						# The if statement. Elif clauses are handled
	type		int			# Using multiple if nodes
	test		NodePtr		# If test
	ifPart		NodePtr		# Then ifPart
	elsePart	NodePtr		# Else elsePart

NWHILE NBinary				# The while statement. First child is the test
NUNTIL NBinary				# The until statement

NFOR NFor					# The for statement
	type		int
	args		NodePtr		# For var in args
	body		NodePtr		# Do body; done
	var			string		# The for variable

NCASE NCase					# A case statement
	type		int
	expr		NodePtr		# The word to switch on
	cases		NodePtr		# The list of cases (NCASELIST nodes)

NCASELIST NCaseList			# A case
	type		int
	next		NodePtr		# The next case in list
	pattern		NodePtr		# List of patterns for this case
	body		NodePtr		# Code to execute for this case

NDEFUN NArg					# Define a function. The "next" field contains
							# the body of the function.
	
NARG NArg					# Represents a word
	type		int
	next		NodePtr		# Next word in list
	text		string		# The text of the word
	backquote	NodeList	# List of commands in back quotes

NTO NFile					# fd > fileName
NFROM NFile					# fd < fileName
NAPPEND NFile				# fd >> fileName
	type		int
	next		NodePtr		# Next redirection in list
	fd			int			# File descriptor being redirected
	fileName	NodePtr		# File name, in a NARG node
	expFileName	temp  char *expFileName	# Actual file name

NTOFD NDup					# fd < &dupFd
NFROMFD NDup				# fd > &dupFd
	type		int	
	next		NodePtr		# Next redirection in list
	fd			int			# File descriptor being redirected
	dupFd		int			# File descriptor to duplicate

NHERE NHere					# fd<<\!
NXHERE NHere				# fd<<!
	type		int
	next		NodePtr		# Next redirection in list
	fd			int			# File descriptor being redirected
	doc			NodePtr		# Input to command (NARG node)












