OBJS = $(ENTRY) main.o read.o pipe.o dmap.o \
	   device.o super.o inode.o \
	   cache.o filedes.o stadir.o \
	   misc.o \
	   utility.o select.o timers.o table.o
NAME = fs
STACK_SIZE = 2048
include ../server.mk
