OBJS = $(ENTRY) main.o open.o read.o write.o pipe.o dmap.o \
	   device.o path.o link.o super.o inode.o \
	   cache.o filedes.o stadir.o protect.o \
	   misc.o utility.o select.o timers.o table.o
NAME = fs
STACK_SIZE = 2048
include ../server.mk
