OBJS = main.o open.o read.o write.o pipe.o dmap.o \
	   device.o path.o mount.o link.o super.o inode.o \
	   cache.o filedes.o stadir.o protect.o time.o \
	   misc.o utility.o select.o timers.o table.o
NAME = fs
STACK_SIZE = 512w
include ../server.mk
