LIB_NAME = mysysutil

OBJS_M32 = kprintf.o \
		   kputc.o \
		   report.o \
		   kmalloc.o \
		   panic.o \
		   getuptime.o \
		   tickdelay.o \
		   env_get_param.o
	

OBJS_M16 = kprintf.o \
		   kmalloc.o

include ../commonlib.mk
