LIB_NAME = mysys

OBJS_M32 = sys_getinfo.o \
		   sys_setalarm.o \
		   sys_getsig.o \
		   sys_endsig.o \
		   sys_sigsend.o \
		   sys_sigreturn.o \
		   sys_vircopy.o \
		   sys_kill.o \
		   sys_trace.o \
		   sys_exit.o \
		   sys_times.o \
		   sys_nice.o \
		   taskcall.o 
		   
	
include ../commonlib.mk
