FROM helowken/myos-base-dev:latest
ENV HOME=/usr/src
ENV BOCHS_NORMAL=$HOME/bochs/build/normal
ENV BOCHS_GDB=$HOME/bochs/build/gdb
COPY .vimrc $HOME
COPY cscope_maps.vim $HOME/.vim/plugin/
COPY ron.vim /usr/share/vim/vim74/colors/
