#ifndef _ERRNO_H
#define _ERRNO_H

#ifdef	_SYSTEM
#	define _SIGN	-
#	define OK		0
#else
#	define _SIGN	
#endif

extern int errno;

#define	EIO			(_SIGN 5)	/* input/output error */
#define ENOEXEC		(_SIGN 8)	/* exec format error */
#define ENOMEM		(_SIGN 12)	/* no enough space */
#define ENOSPC		(_SIGN 28)	/* no space left on device */
#define ERANGE		(_SIGN 34)	/* result too large */

/* The following are not POSIX errors, but they can still happen.
 * All of these are generated by the kernel and relate to message passing.
 */
#define EDONTREPLY	(_SIGN 201)	/* pseudo-code: don't send a reply. */

#endif
