#ifndef _ERRNO_H
#define _ERRNO_H

#ifdef	_SYSTEM
#	define _SIGN	-
#	define OK		0
#else
#	define _SIGN	
#endif

extern int errno;

#define EGENERIC		(_SIGN 99)	/* Generic error */
#define	EPERM			(_SIGN 1)	/* Operation not permitted */
#define ENOENT			(_SIGN 2)	/* No such file or directory */
#define ESRCH			(_SIGN 3)	/* No such process */
#define EINTR			(_SIGN 4)	/* Interrupted function call */
#define	EIO				(_SIGN 5)	/* Input/output error */
#define ENXIO			(_SIGN 6)	/* No such device or address */
#define E2BIG			(_SIGN 7)	/* Arg list too long */
#define ENOEXEC			(_SIGN 8)	/* Exec format error */
#define EBADF			(_SIGN 9)	/* Bad file descriptor */
#define ECHILD			(_SIGN 10)	/* No child process */
#define EAGAIN			(_SIGN 11)	/* Resource temporarily unavailable */
#define ENOMEM			(_SIGN 12)	/* No enough space */
#define EACCES			(_SIGN 13)	/* Permission denied */
#define EFAULT			(_SIGN 14)	/* Bad address */
#define ENOTBLK			(_SIGN 15)	/* Extension: not a block special file */
#define EBUSY			(_SIGN 16)	/* Resource busy */
#define EEXIST			(_SIGN 17)	/* File exists */
#define EXDEV			(_SIGN 18)	/* Improper link */
#define ENODEV			(_SIGN 19)	/* No such device */
#define ENOTDIR			(_SIGN 20)	/* Not a directory */
#define EISDIR			(_SIGN 21)	/* Is a directory */
#define EINVAL			(_SIGN 22)	/* Invalid argument */
#define ENFILE			(_SIGN 23)  /* Too many open files in system */
#define EMFILE			(_SIGN 24)	/* Too many open files */
#define ENOTTY			(_SIGN 25)	/* Inappropriate I/O control operation */
#define ETXTBSY			(_SIGN 26)	/* No longer used */
#define EFBIG			(_SIGN 27)	/* File too large */
#define ENOSPC			(_SIGN 28)	/* No space left on device */
#define ESPIPE			(_SIGN 29)	/* Invalid seek */
#define EROFS			(_SIGN 30)	/* Read-only file system */
#define EMLINK			(_SIGN 31)	/* Too many links */
#define EPIPE			(_SIGN 32)	/* Broken pipe */
#define EDOM			(_SIGN 33)	/* Domain error (from ANSI C std) */
#define ERANGE			(_SIGN 34)	/* Result too large */
#define EDEADLK			(_SIGN 35)	/* Resource deadlock avoided */
#define ENAMETOOLONG	(_SIGN 36)	/* File name too long */
#define ENOLCK			(_SIGN 37)	/* No locks available */
#define ENOSYS			(_SIGN 38)	/* Function not implemented */
#define ENOTEMPTY		(_SIGN 39)	/* Directory not empty */

/* The followng errors relate to networking. */
#define EPACKSIZE		(_SIGN 50)	/* Invalid packet size for some protocol */
#define EOUTOFBUFS		(_SIGN 51)	/* Not enough buffers left */
#define EBADIOCTL		(_SIGN 52)	/* Illegal ioctl for device */
#define EBADMODE		(_SIGN 53)	/* Bad mode in ioctl */
#define EWOULDBLOCK		(_SIGN 54)
#define EBADDEST		(_SIGN 55)	/* Not a valid destination address */
#define EDSTNOTRCH		(_SIGN 56)	/* Destination not reachable */
#define EISCONN			(_SIGN 57)	/* Already connected */
#define EADDRINUSE		(_SIGN 58)	/* Address in use */
#define ECONNREFUSED	(_SIGN 59)	/* Connection refused */
#define ECONNRESET		(_SIGN 60)	/* Connection reset */
#define ETIMEDOUT		(_SIGN 61)	/* Connection timed out */
#define EURG			(_SIGN 62)	/* Urgent data present */
#define ENOURG			(_SIGN 63)	/* No urgent data present */
#define ENOTCONN		(_SIGN 64)	/* No connection (yet or anymore) */
#define ESHUTDOWN		(_SIGN 65)	/* A write call to a shutdown connection */
#define ENOCONN			(_SIGN 66)	/* No such connection */
#define EAFNOSUPPORT	(_SIGN 67)	/* Address family not supported */
#define EPROTONOSUPPORT	(_SIGN 68)	/* Protocol not supported by AF */
#define EPROTOTYPE		(_SIGN 69)	/* Protocol wrong type for socket */
#define EINPROGRESS		(_SIGN 70)	/* Operation now in progress */
#define EADDRNOTAVAIL	(_SIGN 71)	/* Can't assign requested address */
#define EALREADY		(_SIGN 72)	/* Connection already in progress */
#define EMSGSIZE		(_SIGN 73)	/* Message too long */

/* The following are not POSIX errors, but they can still happen.
 * All of these are generated by the kernel and relate to message passing.
 */
#define ELOCKED			(_SIGN 101) /* Can't send message due to deadlock. */
#define EBADCALL		(_SIGN 102)	/* Illegal system call number. */
#define EBADSRCDST		(_SIGN 103)	/* Bad source or destination process. */
#define ECALLDENIED		(_SIGN 104)	/* No permission for system call. */
#define EDEADDST		(_SIGN 105) /* Send destination is not alive. */
#define ENOTREADY		(_SIGN 106) /* Source or destination is not ready. */
#define EBADREQUEST		(_SIGN 107) /* Destination cannot handle request. */
#define EDONTREPLY		(_SIGN 201)	/* Pseudo-code: don't send a reply. */

#endif
