#ifndef _STDLIB_H
#define _STDLIB_H

#include <stddef.h>

#define EXIT_FAILURE	1		/* Standard error return using exit() */
#define EXIT_SUCCESS	0		/* Successful return using exit() */
#define RAND_MAX		32767	/* Largest value generated by rand() */
#define MB_CUR_MAX		1		/* Max value of multibyte character in MINIX */

typedef struct {
	int quot;
	int rem; 
} div_t;

typedef struct {
	long quot;
	long rem;
} ldiv_t;

void abort();
int abs(int j);	
int atexit(void (*func)());	
double atof(const char *nptr);	//TODO
int atoi(const char *nptr);
long atol(const char *nptr);
void *calloc(size_t nmemb, size_t size);
div_t div(int numer, int denom);	//TODO
void exit(int status);
void free(void *op);
char *getenv(const char *name);
long labs(long j);
ldiv_t ldiv(long numer, long denom);	//TODO
void *malloc(size_t size);
int mblen(const char *s, size_t n);	//TODO
size_t mbstowcs(wchar_t *dest, const char *src, size_t n);	//TODO
int mbtowc(wchar_t *pwc, const char *s, size_t n);	//TODO
int rand(void);
void *realloc(void *op, size_t size);
void srand(unsigned int seed);
double strtod(const char *nptr, char **endptr);
long int strtol(const char *nptr, char **endptr, int base);
int system(const char *command);
size_t wcstombs(char *s, const wchar_t *pwcs, size_t n);	//TODO
int wctomb(char *s, wchar_t wchar);	//TODO
void *bsearch(const void *key, const void *base, size_t nmemb, size_t size,
			int (*compar)(const void *, const void *));
void qsort(void *base, size_t nmemb, size_t size, 
			int (*compar)(const void *, const void *));
unsigned long int strtoul(const char *nptr, char **endptr, int base);

#ifdef _POSIX_SOURCE
/* Open Group Base specifications Issue 6 */
int mkstemp(char *fmt);
char *initstate(unsigned seed, char *state, size_t size);	//TODO
long random(void);	//TODO
char *setstate(const char *state);	//TODO
void srandom(unsigned seed);	//TODO
#endif

#ifdef _MINIX
int putenv(const char *string);
#endif

#endif
